FROM node:16-alpine3.12

LABEL version="1"
LABEL description="React Frontend for Kanban API"

WORKDIR /app

COPY ./package*.json ./

RUN npm install

COPY . .

# to solve some permissions issues
RUN mkdir /app/node_modules/.vite \
  && chown -R node:node /app/node_modules/.vite

USER node

CMD [ "npm", "run", "dev" ]