services:
  api:
    build:
      context: ./server
      dockerfile: ../docker/local/django/Dockerfile
    command: /start
    volumes:
      - ./server:/app
      - static_volume:/app/staticfiles
    # ports:
    #   - "8000:8000"
    env_file:
      - ./server/.env
    depends_on:
      - db
    networks:
      - kanban-net
  
  db:
    image: postgres:14-alpine
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - kanban-net
  
  nginx:
    restart: always
    build:
      context: ./docker/local/nginx 
      dockerfile: Dockerfile 
    volumes:
      - static_volume:/app/staticfiles 
    ports:
      - "8081:80"
    depends_on:
      - api
    networks:
      - kanban-net

networks:
  kanban-net:
    driver: bridge

volumes:
  static_volume:
  postgres_data:
